import type { paths } from './generated/gateway'

export type GatewayPath = keyof paths

export const ACTIVE_GATEWAY_PATHS = [
  '/healthz',
  '/readyz',
  '/api/v1/app-version/freshness',
  '/api/v1/users',
  '/api/v1/sessions',
  '/api/v1/sessions/current',
  '/api/v1/users/me',
  '/api/v1/users/me/profile',
  '/api/v1/users/me/password-changes',
  '/api/v1/knowledge-bases',
  '/api/v1/knowledge-bases/{knowledgeBaseId}',
  '/api/v1/knowledge-bases/{knowledgeBaseId}/documents',
  '/api/v1/documents/{documentId}',
  '/api/v1/documents/{documentId}/chunks',
  '/api/v1/documents/{documentId}/content',
  '/api/v1/knowledge-queries',
  '/api/v1/admin/users',
  '/api/v1/admin/users/{userId}',
  '/api/v1/admin/users/{userId}/password-resets',
  '/api/v1/admin/model-profiles',
  '/api/v1/admin/model-profiles/{profileId}',
  '/api/v1/admin/parser-configs',
  '/api/v1/admin/parser-configs/{parserConfigId}',
  '/api/v1/admin/overview',
  '/api/v1/admin/metrics',
  '/api/v1/report-types',
  '/api/v1/report-templates',
  '/api/v1/report-templates/{reportTemplateId}',
  '/api/v1/report-templates/{reportTemplateId}/structure',
  '/api/v1/report-materials',
  '/api/v1/report-materials/{materialId}',
  '/api/v1/reports',
  '/api/v1/reports/{reportId}',
  '/api/v1/reports/{reportId}/outlines',
  '/api/v1/reports/{reportId}/outlines/{outlineId}',
  '/api/v1/reports/{reportId}/outlines/{outlineId}/sections/{sectionId}',
  '/api/v1/reports/{reportId}/sections',
  '/api/v1/reports/{reportId}/sections/{sectionId}',
  '/api/v1/reports/{reportId}/sections/{sectionId}/versions',
  '/api/v1/reports/{reportId}/jobs',
  '/api/v1/report-jobs/{jobId}',
  '/api/v1/report-jobs/{jobId}/attempts',
  '/api/v1/reports/{reportId}/events',
  '/api/v1/report-files',
  '/api/v1/report-files/{reportFileId}',
  '/api/v1/report-files/{reportFileId}/content',
  '/api/v1/report-statistics/overview',
  '/api/v1/report-statistics/daily',
  '/api/v1/report-operation-logs',
  '/api/v1/report-settings',
  '/api/v1/qa-sessions',
  '/api/v1/qa-sessions/{sessionId}',
  '/api/v1/qa-sessions/{sessionId}/messages',
  '/api/v1/qa-sessions/{sessionId}/events',
  '/api/v1/qa-sessions/{sessionId}/attachments',
  '/api/v1/qa-sessions/{sessionId}/attachments/{attachmentId}',
  '/api/v1/response-runs/{responseRunId}',
  '/api/v1/response-runs/{responseRunId}/tool-calls',
  '/api/v1/messages/{messageId}/citations',
  '/api/v1/citations/{citationId}',
  '/api/v1/citation-lookups',
  '/api/v1/qa-config-versions/current',
  '/api/v1/qa-config-versions',
  '/api/v1/llm-config-versions/current',
  '/api/v1/llm-config-versions',
  '/api/v1/llm-connection-tests',
  '/api/v1/retrieval-test-runs',
  '/api/v1/retrieval-test-runs/{testRunId}',
  '/api/v1/qa-metrics/overview',
  '/api/v1/qa-metrics/trend',
  '/api/v1/qa-metrics/top-queries',
  '/api/v1/qa-metrics/intent-distribution',
] as const satisfies readonly GatewayPath[]

export const activeGatewayPathSet: ReadonlySet<string> = new Set(ACTIVE_GATEWAY_PATHS)
